stages:
  - build_windows
  - build_linux
  - build_mac

build-job-linux:
  stage: build_linux
  variables:
    GIT_STRATEGY: none
    ARTIFACT_STRIP_PATH: "viewer/build-linux-x86_64/newview"

  script:
    - echo $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR
    - rm -rf viewer
    - echo $CI_REPOSITORY_URL
    - echo $CI_COMMIT_SHA
    - git clone $CI_REPOSITORY_URL viewer
    - ls --full
    - cd $CI_PROJECT_DIR/viewer
    - echo $CI_PROJECT_DIR/viewer
    - ls --full
    - pwd
    - git reset --hard $CI_COMMIT_SHA
    - git submodule update --init --recursive
    - cd ..
    - pwd
    - chmod +x ./viewer/ci/linux/build.sh
    - chmod +x ./viewer/ci/linux/upload-symbols.sh
    - ./viewer/ci/linux/build.sh
    - ./viewer/ci/linux/upload-symbols.sh
  tags:
    - build
    - linux
  artifacts:
    when: on_success
    paths:
      - viewer/build-linux-x86_64/newview/Phoenix-*.xz
      - viewer/build-linux-x86_64/newview/Phoenix-*.bz2
  resource_group: global_pipeline_lock

build-job-windows:
  stage: build_windows
  variables:
    GIT_STRATEGY: none
    ARTIFACT_STRIP_PATH: "viewer/build-vc170-64/newview/Release"
  script:
    - echo Changing to work dir %CI_PROJECT_DIR%
    - cd %CI_PROJECT_DIR%
    - echo Cloning %CI_REPOSITORY_URL% to viewer
    - git clone %CI_REPOSITORY_URL% viewer
    - echo Resetting to commit $CI_COMMIT_SHA
    - git reset --hard $CI_COMMIT_SHA
    - echo Running batch script $CI_PROJECT_DIR/viewer/ci/windows/launch.bat $CI_PROJECT_DIR $CI_COMMIT_SHA
    - $CI_PROJECT_DIR/viewer/ci/windows/launch.bat $CI_PROJECT_DIR $CI_COMMIT_SHA
  tags:
    - build
    - windows
  artifacts:
    when: on_success
    paths:
      - viewer\build-vc170-64\newview\Release\Phoenix*.exe

build-job-mac:
  stage: build_mac
  script:
    - echo $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR
    - rm -rf viewer
    - echo $CI_REPOSITORY_URL
    - echo $CI_COMMIT_SHA
    - git clone $CI_REPOSITORY_URL
    - cd viewer
    - git reset --hard $CI_COMMIT_SHA
    - git submodule update --init --recursive
    - cd ..
    - cp /Users/jordan/Projects/build.sh .
    - cp /Users/jordan/Projects/upload-symbols.sh .
    - pwd
    - ./build.sh
    - ./upload-symbols.sh
  tags:
    - build
    - macos
  artifacts:
    when: on_success
    paths:
      - viewer/build-darwin-x86_64/newview/Phoenix-*.dmg
  resource_group: global_pipeline_lock
  variables:
    GIT_STRATEGY: none
    ARTIFACT_STRIP_PATH: "viewer/build-darwin-x86_64/newview"